name: "Lingora"
description: "Run Lingora CLI in CI using official release binaries"

inputs:
    args:
        description: "Arguments to pass to lingora-cli"
        required: false
        default: ""

    working-directory:
        description: "Directory to run Lingora in"
        required: false
        default: "."

    version:
        description: "The version of lingora-cli to use; e.g. v0.3.7"
        required: false
        default: ""

runs:
    using: "composite"
    steps:
        - name: Determine executable
          id: target
          shell: bash
          run: |
              set -euo pipefail

              if [ "$RUNNER_OS" = "Windows" ]; then
                TARGET="lingora-cli-windows-latest.exe"
              else
                OS_LOWER="${RUNNER_OS,,}"
                TARGET="lingora-cli-${OS_LOWER}-latest"
              fi

              echo "TARGET=$TARGET" >> $GITHUB_ENV

        - name: Determine version
          shell: bash
          run: |
              set -euo pipefail

              if [ -n "${{ inputs.version }}" ]; then
                VERSION="${{ inputs.version }}"
                echo "Using provided version: $VERSION"
              else
                echo "Resolving latest release from GitHub API..."

                VERSION=$(curl -fsSL \
                  -H "Accept: application/vnd.github+json" \
                  https://api.github.com/repos/nigeleke/lingora/releases/latest \
                  | grep '"tag_name":' \
                  | sed -E 's/.*"([^"]+)".*/\1/')

                if [ -z "$VERSION" ]; then
                  echo "Failed to resolve latest release"
                  exit 1
                fi

                echo "Resolved latest version: $VERSION"
              fi

              echo "VERSION=$VERSION" >> "$GITHUB_ENV"

        - name: Download Lingora
          shell: bash
          run: |
              set -euo pipefail

              BINDIR="${{ runner.temp }}/lingora-bin"
              mkdir -p "$BINDIR"

              URL="https://github.com/nigeleke/lingora/releases/download/${VERSION}/${TARGET}"
              echo "Downloading '$URL'"
              curl -sSL --fail-with-body -o "$BINDIR/lingora-cli" "$URL" || {
                echo "Download failed — probably wrong tag or asset name."
                echo "Check: https://github.com/nigeleke/lingora/releases/tag/${VERSION}"
                exit 1
              }
              ls -al

              if [ "$RUNNER_OS" != "Windows" ]; then
                chmod +x "$BINDIR/lingora-bin/lingora-cli"
                ls "$BINDIR"
                ls "$BINDIR"/lingora-bin
              fi

        - name: Run Lingora
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          run: |
              set -euo pipefail
              ls -al
              echo "****"
              echo ${{ inputs.working-directory }}
              echo "****"
              echo '"$TARGET"'
              echo '"$BINDIR/lingora-bin/"$TARGET"'
              echo "****"
              "$BINDIR/lingora-bin/"$TARGET" ${{ inputs.args }}
