name: "Lingora"
description: "Run Lingora CLI in CI using official release binaries"

inputs:
    version:
        description: "Lingora version (e.g. v0.3.2). Defaults to the action ref."
        required: false
        default: ""

    args:
        description: "Arguments to pass to lingora-cli"
        required: false
        default: ""

    working-directory:
        description: "Directory to run Lingora in"
        required: false
        default: "."

runs:
    using: "composite"
    steps:
        - name: Determine version
          id: version
          shell: bash
          run: |
              set -euo pipefail

              if [ -n "${{ inputs.version }}" ]; then
                VERSION="${{ inputs.version }}"
              else
                VERSION="${GITHUB_ACTION_REF}"
              fi

              echo "VERSION=$VERSION" >> $GITHUB_ENV

        - name: Determine executable
          id: target
          shell: bash
          run: |
              set -euo pipefail

              if [ "$RUNNER_OS" = "Windows" ]; then
                TARGET="lingora-cli-windows-latest.exe"
              else
                OS_LOWER="${RUNNER_OS,,}"
                TARGET="lingora-cli-${OS_LOWER}-latest"
              fi

              echo "TARGET=$TARGET" >> $GITHUB_ENV

        - name: Download Lingora
          shell: bash
          run: |
              set -euo pipefail

              URL="https://github.com/nigeleke/lingora/releases/download/${VERSION}/${TARGET}"

              echo "Downloading $URL"
              curl -sSL -o "$TARGET" "$URL"
              ls -al

              if [ "$RUNNER_OS" != "Windows" ]; then
                chmod +x "$TARGET"
                ls -al
              fi

        - name: Run Lingora
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          run: |
              set -euo pipefail
              ls -al
              echo "****"
              echo ${{ inputs.working-directory }}
              echo "****"
              echo "$TARGET"
              echo "****"
              ./"$TARGET" ${{ inputs.args }}
