# Run acceptance-cycle on develop commits.
#
# Acceptance cycle comprises:
# - run tests on develop
# - release into main with bumped versions
#
name: Acceptance Cycle

on:
    workflow_run:
        workflows: ["Commit Cycle"]
        branches: [develop]
        types:
            - completed

env:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8

jobs:
    acceptance:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        steps:
            - name: Updates
              run: |
                  sudo apt update
                  sudo apt install libwebkit2gtk-4.1-dev \
                    build-essential \
                    curl \
                    wget \
                    file \
                    libxdo-dev \
                    libssl-dev \
                    libayatana-appindicator3-dev \
                    librsvg2-dev
                  wget https://apt.llvm.org/llvm.sh
                  chmod +x llvm.sh
                  sudo ./llvm.sh 19
                  cargo install cargo-binstall
                  cargo binstall dioxus-cli

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: "0"
                  ref: "develop"

            - name: Test
              run: |
                  cargo test
                  rustup toolchain install nightly
                  rustup component add llvm-tools-preview --toolchain nightly
                  cargo install cargo-llvm-cov
                  cargo llvm-cov --cobertura --output-path=cobertura.xml

            - name: Publish to Codecov
              uses: codecov/codecov-action@v5
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

            - name: Documentation
              run: |
                  cargo doc --no-deps

    release:
        needs: acceptance
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: "main"

            - name: Build
              run: |
                  git config --global user.email "nigeleke@users.noreply.github.com"
                  git config --global user.name "Nigel Eke"
                  git merge origin/develop
                  cargo install cargo-workspaces
                  cargo workspaces -v version --allow-branch main --yes patch
