# Quick feedback for unit tests on non-main commits.
#
name: Commit Cycle

on:
    push:
        branches-ignore:
            - main

env:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Updates
              run: |
                  sudo apt install -y libwebkit2gtk-4.1-dev libsoup3.0-dev

            - name: Checkout
              uses: actions/checkout@v4

            - name: Compile
              run: |
                  cargo build

            - name: Lint
              run: |
                  cargo clippy

            - name: Test
              run: |
                  cargo test
