# Quick feedback for unit tests on non-main commits.
#
name: Commit Cycle

on:
    push:
        branches: [main]

env:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Tooling
              run: |
                  sudo apt update
                  sudo apt install libwebkit2gtk-4.1-dev \
                    build-essential \
                    curl \
                    wget \
                    file \
                    libxdo-dev \
                    libssl-dev \
                    libayatana-appindicator3-dev \
                    librsvg2-dev \
                    libglib2.0-dev
                  rustup update
                  rustup component add clippy
                  wget https://apt.llvm.org/llvm.sh
                  chmod +x llvm.sh
                  sudo ./llvm.sh 19
                  cargo install cargo-binstall
                  cargo binstall dioxus-cli

            - name: Compile
              run: |
                  cargo build

            - name: Lint
              run: |
                  cargo clippy

            - name: Test
              run: |
                  cargo test
