# Quick feedback for unit tests on non-main commits.
#
name: Commit Cycle

on:
    push:
        branches-ignore:
            - main

env:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Updates
              run: |
            - name: Updates
              run: |
                  sudo apt update \
                  && sudo apt install -y -qq \
                    libwebkit2gtk-4.1-dev \
                    build-essential \
                    curl \
                    wget \
                    file \
                    libxdo-dev \
                    libssl-dev \
                    libayatana-appindicator3-dev \
                    librsvg2-dev \
                    llvm \
                  && cargo install --quiet cargo-binstall \
                  && cargo binstall --quiet dioxus-cli

            - name: Checkout
              uses: actions/checkout@v4

            - name: Compile
              run: |
                  cargo build --quiet

            - name: Lint
              run: |
                  cargo clippy --quiet

            - name: Test
              run: |
                  cargo test --quiet
