# Manual release of bumped major version.
name: Release Major

on:
    workflow_dispatch:
        inputs:
            releaseType:
                description: "Release type"
                required: true
                default: "minor"
                type: choice
                options:
                    - major
                    - minor

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: "main"

            - name: Build
              run: |
                  git config --global user.email "nigeleke@users.noreply.github.com"
                  git config --global user.name "Nigel Eke"
                  cargo install cargo-workspaces
                  cargo workspaces -v version --allow-branch main --yes ${{ inputs.releaseType }}
