# Run publish-cycle on main commits.
#
# Publish cycle comprises:
# - publish site, coverage reports and API documentation to https://nigeleke.github.io
#
name: Publish Cycle

on:
    workflow_run:
        workflows: ["Acceptance Cycle"]
        branches: [main]
        types:
            - completed

env:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8

jobs:
    publish:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Tooling
              run: |
                  sudo apt update
                  sudo apt install libwebkit2gtk-4.1-dev \
                    build-essential \
                    curl \
                    wget \
                    file \
                    libxdo-dev \
                    libssl-dev \
                    libayatana-appindicator3-dev \
                    librsvg2-dev \
                    libglib2.0-dev
                  rustup update
                  rustup component add clippy
                  rustup toolchain install nightly
                  rustup component add llvm-tools-preview --toolchain nightly
                  wget https://apt.llvm.org/llvm.sh
                  chmod +x llvm.sh
                  sudo ./llvm.sh 19
                  cargo install cargo-llvm-cov
                  cargo install cargo-binstall
                  cargo binstall dioxus-cli

            - name: Build Site
              run: |
                  cargo doc --no-deps
                  cargo llvm-cov --html
                  mkdir docs0
                  mkdir -p docs0/api
                  mkdir -p docs0/coverage
                  cp README.md docs0/
                  cp -R target/doc/* docs0/api
                  cp -R target/llvm-cov/html/* docs0/coverage/
                  cargo llvm-cov --cobertura --output-path=cobertura.xml

            - name: Publish to Codecov
              uses: codecov/codecov-action@v5
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

            - name: Publish to Codecov Housekeeping
              run: |
                  rm cobertura.xml
                  rm codecov
                  rm codecov.SHA256SUM
                  rm codecov.SHA256SUM.sig

            - name: Publish App & Documentation
              run: |
                  git config --global user.email "nigeleke@users.noreply.github.com"
                  git config --global user.name "Nigel Eke"
                  export VERSION=$(git describe --abbrev=0 --tags)
                  git checkout gh-pages
                  rm -rf docs
                  mv docs0 docs
                  git add .
                  git commit -m "Release $VERSION"
                  git push
